### ISSUE TITLE
Enable static builds of binaries

### ISSUE THREAD

**Issue by rainbreak** [ethereum/webthree-umbrella#495]
Following on from ethereum/webthree-helpers#157, enable static linking of some more binaries by switching `add_executable` to `eth_simple_add_executable`.

This is a master issue. Target binaries:
- [x] `eth` 
  - [x] wrap `add_exe` ethereum/webthree#163
- [x] `solc` ethereum/solidity#528
- [x] `soltest` ^
- [x] `lllc` ^
  - [x] fix macro arguments ethereum/webthree-helpers#164
- [ ] `ethminer` 
  - [x] wrap `add_exe` ethereum/libethereum#248
  - [ ] macro changed.   dynamic working.   static still has `-lcurl` ordering issue
- [x] Fix accidental REQUIRED introduced onto curl for dynamic builds (https://github.com/ethereum/webthree-helpers/pull/165)
- [ ] Usage of `STATIC_LINKING` across platforms
  - [x] Test static linkage on Alpine Linux
  - [ ] Test static linkage on Debian (working, you said?) (no, curl link problems)
  - [ ] Test static linkage on Ubuntu
  - [x] Test static linkage on OS X (partial static-linkage working).
    - [ ] Suppress some [linker warnings](http://stackoverflow.com/questions/4929255/building-static-libraries-on-mac-using-cmake-and-gcc)
  - [ ] Test static linkage on Windows

**Comment by rainbreak** [comment]
Just running a local build now to sanity check the above build with static linking.

**Comment by rainbreak** [comment]
Everything works except `ethminer` which fails on linking with a curl problem:

```
[100%] Linking CXX executable ethminer
/src/built/lib/libjsonrpccpp-client.a(httpclient.cpp.o): In function `jsonrpc::HttpClient::HttpClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
httpclient.cpp:(.text+0x14d): undefined reference to `curl_easy_init'
/src/built/lib/libjsonrpccpp-client.a(httpclient.cpp.o): In function `jsonrpc::HttpClient::~HttpClient()':
httpclient.cpp:(.text+0x1e4): undefined reference to `curl_easy_cleanup'
/src/built/lib/libjsonrpccpp-client.a(httpclient.cpp.o): In function `jsonrpc::HttpClient::SendRPCMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
httpclient.cpp:(.text+0x2b5): undefined reference to `curl_easy_setopt'
...
```

**Comment by bobsummerwill** [comment]
Link order issue?   A la http://stackoverflow.com/questions/28165518/use-libcurl-undefined-reference-to-curl-easy-init?

**Comment by rainbreak** [comment]
That's puzzling. Not sure why it isn't an issue when building `eth`, which also uses `jsonrpccpp`.

**Comment by bobsummerwill** [comment]
Well, if it just a command-line order issue, it would all just be down to the order in which targets were executed.    So maybe just some fluky alphabetical thing, where -lcurl is ending up early in this case?

**Comment by rainbreak** [comment]
This is the actual link command (formatted):

```
/src/webthree-umbrella/build # cat libethereum/ethminer/CMakeFiles/ethminer.dir/link.txt 

/usr/bin/c++   -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -Werror -pedantic -DSHAREDLIB -fPIC
-std=c++11 -Wall -Wno-unknown-pragmas -Wextra -Werror -pedantic -DSHAREDLIB -fPIC
-Wno-error -fstack-protector-strong -Wstack-protector -O3 -DNDEBUG -DETH_RELEASE  -static

CMakeFiles/ethminer.dir/main.cpp.o  -o ethminer -rdynamic 
/src/built/lib/libjsoncpp.a 

-lssh2 -lssl -lcrypto -lz -lcurl                     <------------- curl link
/src/built/lib/libjsonrpccpp-common.a 
/src/built/lib/libjsonrpccpp-client.a

/src/built/lib/libjsoncpp.a
/src/built/lib/libleveldb.a 
-lboost_thread-mt -lboost_random -lboost_filesystem -lboost_system -lpthread 
../../libweb3core/libdevcore/libdevcore.a 
../../webthree-helpers/utils/libscrypt/libscrypt.a /src/built/lib/libcryptlib.a 
../../webthree-helpers/utils/secp256k1/libsecp256k1.a

../../libweb3core/libdevcrypto/libdevcrypto.a 
../libethcore/libethcore.a 
../libevmcore/libevmcore.a
../libevm/libevm.a 
/src/built/lib/libminiupnpc.a 
../../libweb3core/libp2p/libp2p.a 
-lboost_regex

../libethereum/libethereum.a 
/src/built/lib/libcryptlib.a 
../libethash/libethash.a
../libethashseal/libethashseal.a 
../libethereum/libethereum.a 
../libevm/libevm.a 
../libethcore/libethcore.a
../libevmcore/libevmcore.a 
../../libweb3core/libp2p/libp2p.a 
../../libweb3core/libdevcrypto/libdevcrypto.a
../../libweb3core/libdevcore/libdevcore.a 
/src/built/lib/libjsoncpp.a 
/src/built/lib/libleveldb.a 
-lboost_thread-mt -lboost_random -lboost_filesystem -lboost_system -lpthread
../../webthree-helpers/utils/libscrypt/libscrypt.a 
../../webthree-helpers/utils/secp256k1/libsecp256k1.a 
-lgmp /src/built/lib/libminiupnpc.a -lboost_regex 
../libethash/libethash.a /src/built/lib/libcryptlib.a 
```

I notice that ethminer isn't linking the json rpc server, only the client, so maybe there is some problem from there.

**Comment by rainbreak** [comment]
Manually appending `-lcurl -lssh2 -lssl -lcrypto -lssl -lcrypto -lz` fixes it (that's the output of `pkg-config --libs --static libcurl`). Now just need to coerce cmake into adding it.

**Comment by bobsummerwill** [comment]
'I notice that ethminer isn't linking the json rpc server, only the client, so maybe there is some problem from there."

^ Yeah.  I think that this whole stack of "JSON-RPC stuff" which then drags in the curl chain is all a very thin thread of dependencies, but which is a bit messy.     I did some minimization before which removed the unnecessary JsonRpc::Server dependency from ethminer.   There is probably plenty more which can be trimmed, if we better understood it.

Good luck!

**Comment by bobsummerwill** [comment]
So it looks like part of my CURL REQUIRED thing was due to only having a partially synced workspace, but I've made one clean up which is building now, and then that's good and everything is healthy for the dynamic builds and you just have that curl link order thing for ethminer left.

I'm going to try doing static builds for OS X and Windows now, for eth at least, and hopefully more if I have time.

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/webthree-helpers/pull/167.

**Comment by rainbreak** [comment]
I've got a Dockerfile for building (unsuccessfully) on Debian here:

https://github.com/rainbeam/eth-static/blob/debian/Dockerfile

Really minimal curl can be configured with:

```
./configure --prefix=/opt/curl --enable-static --disable-shared \
--disable-ldap --disable-ldaps --without-libidn --disable-rtsp --without-librtmp \
--disable-manual --disable-tls-srip --without-gnutls \
--without-ssl --without-libssh2 --without-zlib
```

However, even if we get past the curl linking problems, there is a bigger problem in that glibc is not designed to be statically linked. The `STATIC_LINKING` that I've implemented tries to static link everything. This works fine on a musl based platform (i.e. Alpine), but isn't going to work on Debian / Ubuntu. I don't know what the story is on Windows.

The binary this produces is completely portable across Linux based distros though - the limitation is only in the build environment.

As such, I don't regard the Debian / Ubuntu problems as part of this issue. The `ethminer` problem is still relevant though.

As for other platforms (other than x86_64)... I've not looked into it much but I saw that there are musl cross compilers provided here:

http://musl.codu.org/

Might be useful in your mobile adventures :smile: .

**Comment by bobsummerwill** [comment]
Thanks for that extra info, which will indeed be useful.   Flipping to a statically linked musl cross-compiled runtime could be very useful.

I found that OS X as does not want to be completely statically linked (see https://developer.apple.com/library/mac/qa/qa1118/_index.html), so added checks for that to give an error message rather than just failing.    I will try to "weaken that off", so that it statically links everything except the C++ runtime library.

Windows can be used with either DLLs or static libraries for the runtime.    That will because unlike Linux, there is a binary compatibility guarantee for Windows, which is why old Windows apps work for years and years.    Linux, I understand, has never had that, hence the monolithic kernel including drivers for everything under the sun.     They have to be in-tree because the ABI can change arbitrarily between kernel and drivers.

Seems the ABI guarantee is a bit weak on OS X too.

As for curl, yeah, would be great to do a minimal compile like that, and I will certainly refer back to your notes here as-and-when I get around to pulling that in as a sub-module.

Did you try building curl like that for your Alpine Linux build?   So with such settings, if looks like OpenSSL, ssh2 and zlib would NOT be needed?

**Comment by bobsummerwill** [comment]
"Manually appending -lcurl -lssh2 -lssl -lcrypto -lssl -lcrypto -lz fixes it (that's the output of pkg-config --libs --static libcurl). Now just need to coerce cmake into adding it."

^ Did you manage to work out the magic spell for this, btw? :-)

**Comment by rainbreak** [comment]
No. I messed around a bit with moving the `eth_use(CURL)` around and with linking against a minimal libcurl, but no luck. Stopped short of doing a full debug of how CMake constructs its linker arguments. It doesn't have a verbose logging mode, so I think you have to debug by adding lots of `message` calls.

Also tried a bit more with Debian. I reckon it is possible to build fully static by using `musl-gcc` from `musl-tools`, but still ran into problems with linking curl.

https://github.com/rainbeam/eth-static/tree/ethminer

https://github.com/rainbeam/eth-static/tree/debian

~~Did you have a look at Windows?~~ (sorry missed your post above)

**Comment by rainbreak** [comment]
Just did an Alpine build with minimal curl - ssh2, openssl and zlib appear not to be needed.

**Comment by bobsummerwill** [comment]
Thanks for the update.

I've been doing a partially static build for OS X, with some success, and will try Windows as well when I get a chance.

"Just did an Alpine build with minimal curl - ssh2, openssl and zlib appear not to be needed." - That is good to know, and makes sense.

OS X static build is pulling in Snappy as an indirect dependency of leveldb, which is a bit weird, but I suspect it is just an artifact of the fact that leveldb is still a dylib dependency at the partial stage I got to:

```
[100%] Linking CXX executable eth
[100%] Built target eth
Bobs-MacBook-Air:build bob$ otool -L webthree/eth/eth
webthree/eth/eth:
    /usr/local/opt/jsoncpp/lib/libjsoncpp.1.dylib (compatibility version 1.0.0, current version 1.6.5)
    /usr/local/opt/leveldb/lib/libleveldb.1.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/miniupnpc/lib/libminiupnpc.15.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
    /usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
    /usr/local/opt/libjson-rpc-cpp/lib/libjsonrpccpp-common.0.dylib (compatibility version 0.0.0, current version 0.6.0)
    /usr/local/opt/libjson-rpc-cpp/lib/libjsonrpccpp-client.0.dylib (compatibility version 0.0.0, current version 0.6.0)
    /usr/local/opt/libjson-rpc-cpp/lib/libjsonrpccpp-server.0.dylib (compatibility version 0.0.0, current version 0.6.0)
    /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

So, getting to a static binary isn't possible on OS X, but statically linking all the libs **should** be possible.   The binary I have right now runs just fine, but the following libs are still using .dylib, not .a:
- jsoncpp
- json-rpc-cpp
- leveldb
- miniupnp
- gmp

To get those ones statically linking, I'll need to build them from source.    libz and curl ship as part of the platform, but again I could build them from source and statically link them.

**Comment by bobsummerwill** [comment]
PS.  OS X partially statically linked executable is 12MB.

**Comment by bobsummerwill** [comment]
OK - So testing this for Windows is a horror-show, because we'll need LIB files for all the pre-built external dependencies.   I'm going to defer that for now.

So @rainbeam ... are you pretty much done here now?

And you still didn't work out a magic-mantra to get the libcurl ordering thing resolved, right?   That was on Debian?   Or Alpine?

**Comment by rainbreak** [comment]
Yeah I think I'm done here.

Couldn't resolve the libcurl problem, except by manually modifying the link command after cmake was configured. This only affects `ethminer`. The problem exists on both Alpine and Debian.

Debian has the added problem of glibc, which isn't going to statically link. A similar solution to OSX (i.e. dynamic linking the system libs) might be needed if people want to build on that platform (rather than just use a static binary compiled on a musl system). Alternatively, Debian does have `musl-tools` etc. which may allow actual building of a static binary from Debian. I couldn't quite get this working.

Thanks for your help on this Bob :)

**Comment by bobsummerwill** [comment]
FYI ... My first Boost post made it through their filters ...

http://lists.boost.org/Archives/boost/2016/05/229385.php

... the one about thread setname/getname.

And got a first reply:

http://lists.boost.org/Archives/boost/2016/05/229388.php

**Comment by bobsummerwill** [comment]
See https://github.com/boostorg/thread/issues/84, where there is now an issue tracking the Boost TODO, which I have offered to put on my backlog.

**Comment by bobsummerwill** [comment]
Hey @rainbeam,

I have been working on an infrastructure-as-code alternative to these tedious per-distro sets of instructions, which will "go live" when we switch back to cpp-ethereum.

You can see my work-in-progress on that here:
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/.travis.yml
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh

Now for the TravisCI bit, we're stuck with just Ubuntu Trusty automation for the time being, but we might well be able to expand that via Docker in the future.

Whatever the case, I would like to expand this install_deps.sh pattern pattern to cover more distros, so that our ethdocs.org instructions for the distros which we have bothered to do that can be simplified to, with the steps being executed directly and committed in with the code itself.
- git clone --recursive
- ./install_deps.sh
- cmake
- make

So maybe for Alpine we can take that approach instead, rather than bothering with written instructions?

Please could help me out and copy https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh locally and run it, does it go into the right conditional?

I suspect that it won't work, and that we will need to do something different for Alpine detection.

**Comment by bobsummerwill** [comment]
install_deps request split out into https://github.com/ethereum/webthree-umbrella/issues/633.

**Comment by bobsummerwill** [comment]
Hey @rainbeam!
How are you doing?

See http://doublethinkco.github.io/cpp-ethereum-cross/images/dependency_graph.svg which I've just generated as part of the oh-so-nearly-finished cpp-ethereum Homecoming, including those tricky little bastard curl dependencies!

**Comment by bobsummerwill** [comment]
Are you up for helping me out on the install.sh stuff for Alpine?

I want to get the Alpine flow to be super-simple, so I can add Alpine static-build automation via Docker into our flow.    Because I think that those statically-linked Linux executables are actually going to be THE BEST executables which we can supply on Linux.

See also https://github.com/ethereum/webthree-umbrella/issues/664.

All that bullshit is pretty analogous to this bullshit which I have still to resolve for the cross-builds on Tizen for the Gear S2 smartwatch, which is where I started my whole Ethereum adventure nearly a year ago and still have not solved!

https://github.com/doublethinkco/cpp-ethereum-cross/issues/20

**Comment by bobsummerwill** [comment]
Damn you, GLIBC!

`./eth: /usr/lib/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by ./eth)`

**Comment by bobsummerwill** [comment]
Tizen 2.4 ships with C runtime from the ancient GCC 4.6.

**Comment by rainbreak** [comment]
hey @bobsummerwill: sure I can help out with static Alpine builds. Will be great when I can just download the latest solidity static binary :)

Are we targeting just eth and solc or is it wider than that?

I'm getting a bit lost with the repo reorg. Will there be a install.sh in both solidity and cpp-ethereum repos?

**Comment by bobsummerwill** [comment]
Great!

So the reorg changes aren't live in the final repos, yet, though they will be in the next few days

These are my working branches:
- https://github.com/bobsummerwill/cpp-ethereum/tree/merge_repos
- https://github.com/bobsummerwill/solidity/tree/standalone_prior_to_splat

So, yes, both will have `scripts/install.sh` files, which will be the ones shown above.

**Comment by bobsummerwill** [comment]
And I want to get all executables working with static builds :-)

Thanks for the offer of help.   I'll give you a poke when the repo switches are done and it is less head-scratchy!

**Comment by nerdralph** [comment]
I have been looking into building a static ethminer (based on Genoil's fork), and got almost there.
https://github.com/nerdralph/ethminer-nr/blob/110/releases/ethminer-genoil-1.1.8nr.tgz

I ran into the libcurl issue (without having read this thread first), and my initial "solution" was just to dynamically link libcurl.  Here's what I've figured out in the process:
Ethminer doesn't directly depend on libcurl, that dependency arises from libjson-rpc.  If you check the external dependencies of /usr/lib/libjsonrpccpp-client.so with ldd you'll see libcurl.so.4.  And since there is no direct dependency on curl, it's possible to do a dynamic linked build with curl removed from EthDependencies.cmake.  Doing a mostly static build (with curl still dynamically-linked) isn't as simple as adding "set(CMAKE_FIND_LIBRARY_SUFFIXES .a .so)", and that's because there is no libcurl.so.   When libjsonrpcccpp-client.a is statically linked, libcurl.so needs to be on the link line to resolve the undefined symbols. The convention in Linux is that libcurl.so would be a symlink to libcurl.so.4, and libcurl.so.4 would be a symlink to the actual file, which in the case of Ubuntu 14.04 is libcurl.so.4.3.0 (which is part of the oddly-named libcurl3 package).  But as there's no libcurl.so, my hacked solution was to explicitly list libcurl.so.4 in FindCURL.cmake.  FindOpenCL.cmake does the same kind of thing, so apparently someone before me considered to be a suitable (or the least offensive) work-around.
Today I noticed cmake has a FindCURL module, and thought that might be smart enough to find libcurl.so.X, but it doesn't.
https://cmake.org/cmake/help/v3.0/module/FindCURL.html

I tried using libcurl.a from libcurl4-openssl-dev instead of libcurl4-gnutls-dev, but that wasn't any better.  I think the issue is the plethora of dependencies for ssl support.  My next though is that a custom build of libcurl without ssl may work, since ethminer doesn't use ssl connections.  I had to do something similar (do a local build) for cryptopp.  I still haven't cleanly integrated that into the cmake files, as I plan to test including cyrptopp as a git submodule.

If anyone has some less-hackish ideas for getting this to work, I'm all ears.  Otherwise, I'll continue to pick away at it.

**Comment by rainbreak** [comment]
@nerdralph: great!

As I recall, I could get ethminer to compile when I manually fiddled with the gcc command that cmake generated, but couldn't get cmake to actually generate it. Also had issues with gnutls, but only on Debian - I found building on an Alpine docker image to be simpler. I _think_ the only curl dep was in jsonrpccpp, and that only seems to need curl itself (no ssl etc.), but cmake doesn't seem to be able to figure that out (even when explicitly told about a bare build of libcurl).

Please keep hacking away! My approach was completely hacky. It'll probably help that you actually use ethminer.

**Comment by nerdralph** [comment]
@rainbeam Thanks for the feedback.  I had started by patching into Genoil's fork the cmake changes that I guess you had committed for static linking.  I was confused at first because some of the changes didn't seem to do anything, but now that I know it's still a work in progress it makes more sense.  I, too, got my first static build by hacking the makefile generated by cmake.  Then I did some more debugging to understand a bit more about the order of execution of the cmake files.
The current state of things is that under Ubuntu 14.04 I use the following command line for my mostly-static build:
cmake -DBUNDLE=miner -DCRYPTOPP_ROOT_DIR=`pwd` -DETH_STATIC=1 ..

I've added a ETH_SHARED to enable building shared libs (for libdevcore, libethcore, etc). 
https://github.com/nerdralph/ethminer-nr/blob/110/cmake/EthCompilerSettings.cmake#L95
The default is now to generate static libs for them (i.e. .a files under Unix), but search for and link shared libs for things like boost.

**Comment by bobsummerwill** [comment]
Thanks to you both!

I think it will be such a big win when we get to the end of this adventure.

Ultimately, I think we're going to want to build all of the external dependencies from source for the degree of control of build options we're going to need for things like libcurl, following @chfast's path with LLVM for evmjit.

You will have seen this updated dependency-graph, right?

https://camo.githubusercontent.com/b59d6b4aa624edfa51c707ac543369c1d90b2e3e/687474703a2f2f646f75626c657468696e6b636f2e6769746875622e696f2f6370702d657468657265756d2d63726f73732f696d616765732f646570656e64656e63795f67726170682e737667

So I was looking at ethminer's dependencies, and I think that it is very likely that we can do some minor refactoring within ethashseal to sever that hard dependency onto libethereum when we are building ethminer.    That will make the `ethminer` dependency tree much more manageable, but you can still see the mess of indirect dependencies dangling off `json-rpc-cpp`.    If we can build a very constrained subset of libcurl from source then maybe that wouldn't be so bad.

**Comment by bobsummerwill** [comment]
If we could do that pruning (https://github.com/ethereum/webthree-umbrella/issues/675) then I think we would end up with the following dependencies for `ethminer`:
- json-rpc-cpp (drags in curl, libedit, argtable2, microhttpd, and maybe zlib and ssh2)
- ethashseal
- ethash
- ethash-cl
- OpenCL (sundry packages)
- CryptoPP
- some boost

**Comment by nerdralph** [comment]
You can easily remove CryptoPP; the code doesn't require it:
https://github.com/ethereum/libethereum/blob/c7f084b6b7841f4cb7c8da5d3dc3a35013f228a9/libethash/internal.c#L41

And to make things a bit cleaner, remove CryptoPP from the CMakefiles (otherwise it clutters up the cmake output when it is not found).

ethminer doesn't use json http server, so just delete MinerAux.h:51 to get rid of the microhttpd dependency (commensurate CMakefile cleanup recommended as well)
https://github.com/ethereum/libethereum/blob/c7f084b6b7841f4cb7c8da5d3dc3a35013f228a9/ethminer/MinerAux.h#L51

**Comment by nerdralph** [comment]
Since Genoil's miner supports stratum and curl is only needed for getwork, I did a stratum-only build and aside from libOpenCL, just has the typical Linux shared library dependencies:
ldd ethminer
        linux-vdso.so.1 =>  (0x00007ffccd66e000)
        libOpenCL.so.1 => /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 (0x00007f7110ee1000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7110cc3000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f71109be000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f71106b8000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f71104a2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f71100dc000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f710fed8000)
        /lib64/ld-linux-x86-64.so.2 (0x00005632f78a5000)

Built with g++ 4.8.4 and lto, the binary is just under 1MB.

**Comment by rainbreak** [comment]
@nerdralph: 1MB is amazing :D is lto the same as doing `strip`?

**Comment by nerdralph** [comment]
I haven't tried it yet, but a build of libcurl from source using "configure --without-ssl" should get rid of the openssl/tls shared lib dependencies.
https://curl.haxx.se/docs/install.html

**Comment by bobsummerwill** [comment]
CryptoPP is slated for death throughout the codebase (https://github.com/ethereum/webthree-umbrella/issues/103), but if we can sever the libethereum dependency for `ethminer` then that can get chopped out before that full cleanup occurs.

RE:  JSON-RPC-Server - Right.     I think you might not even need any CMake file changes, because I think I already did that :-)    We just have a stray include left, which works because the include paths are the same, but could just be deleted.

Could you confirm, @nerdralph, that you could delete that one-liner and it just worked?   No weird .so stuff happening at runtime or build time?   If so, I will chop that out right now!

**Comment by bobsummerwill** [comment]
LTO = link time optimizations, I guess?
Which I suppose is the same as "Whole Program optimization" for VC++?   AKA LTKG - link-time code generation.
yeah - 1MB is nice!
What size were your static-linkage executables again on Alpine, @rainbeam?

**Comment by nerdralph** [comment]
@rainbeam Read my blog and the associated links for info on link time optimization.
http://nerdralph.blogspot.ca/2014/07/gcc-lto-call-graph-generation.html

**Comment by nerdralph** [comment]
@bobsummerwill Deleting httpserver had no impact on Genoil's fork.  Much of the code is still the same, but I'd recommend you do a quick test before pushing it to the repo.

**Comment by rainbreak** [comment]
@bobsummerwill: solc was 3.0M, eth about 10M. That's with post build strip, but without any LTO.

**Comment by bobsummerwill** [comment]
@nerdralph Yep - will test, of course.   Doing so now in https://github.com/bobsummerwill/cpp-ethereum/commits/merge_repos.

@rainbeam Nice sizes.   Yeah - no doubt we can get those down further!

On the LTO theme, another related thing which I was to do is BulkBuild/UnityBuilds (https://github.com/ethereum/webthree-umbrella/issues/415).   Have either of you done those before?   They really are magic, but they work for the same reason as LTO does.    Just stuff all the code for a library together into a single compilation unit and:
1. It builds like 10x faster, because the pre-processor isn't processing all the headers N times (one per compilation unit)
2. And the optimizer can do a better job, because even within each compilation unit, it has "whole program" visibility.

BulkBuild delivers stunning build speed-ups and improves the generated code quality.    It is likely kind of redundant now in terms of optimizations if you have LTCG/LTO in your toolset, but the speed-up is still unique.

**Comment by bobsummerwill** [comment]
BTW - @Genoil - fyi - all this stuff :-)   ^^^^

**Comment by nerdralph** [comment]
@bobsummerwill I've been talking to JW all along.
https://github.com/Genoil/cpp-ethereum/issues/87

**Comment by nerdralph** [comment]
I get a page not found error for the unity link.
http://buffered.io/posts/screencast-setting-up-unity-builds/

**Comment by bobsummerwill** [comment]
Some more unity-build links, @nerdralph:
- https://www.google.ca/?ion=1&espv=2#q=setting+up+unity+builds+C%2B%2B
- https://randomascii.wordpress.com/2014/03/22/make-vc-compiles-fast-through-parallel-compilation/

RE: Talking to Genoil.   Great!

**Comment by nerdralph** [comment]
@bobsummerwill The info you provided on unity/blob builds shows it to be a hack, and it would even seem to break some things (like static in C).
Avoiding nested includes is one thing I recommend for faster compilation and cleaner code.  It's one of the Chromium coding guidelines:
https://www.chromium.org/developers/coding-style/cpp-dos-and-donts

**Comment by nerdralph** [comment]
Just did some testing and found out that lto breaks the build with g++-5.3 and 6.1 :-(

**Comment by bobsummerwill** [comment]
Oh yeah, @nerdralph.

It absolutely is a hack, but a hack with beautiful upside in terms of developer productivity.

It is very easy to counter the downsides, by maintaining both "loose" and 'BulkBuild" modes within your automated build process, but just using "BulkBuild" by default for your local builds.

You do sometimes need to make minor changes to avoid symbol clashes when force-combining compilation units in that way, but they are surprisingly easy to resolve.

The upside is that your builds are like 10x faster, which is a productivity benefit which it is very hard to argue with.

RE: Nested includes ... I don't see that in your referenced Chromium guide.

I have seen old advice saying that you should never include headers within headers, which is god-awful advice.

The bible for a lot of this physical dependencies stuff is 10 years old now, but most C++ developers have never even heard of it :-)

https://www.amazon.ca/Large-Scale-Software-Design-John-Lakos/dp/0201633620

**Comment by bobsummerwill** [comment]
What do those LTO breaks look like, @nerdralph?

**Comment by nerdralph** [comment]
With -flto I was getting lots of undefined refernce errors with gcc-5.3 and gcc-6.1, but not with 4.8.
I remembered having a similar problem before with lto and gcc-4.9, and found where I had read about it:
http://hubicka.blogspot.ca/2014/04/linktime-optimization-in-gcc-2-firefox.html

As a quick hack, I tried renaming ar to ar-binutils and making a symlink to gcc-ar, only to find that it crashed my machine when building!

**Comment by nerdralph** [comment]
@bobsummerwill Re build speedups, I assume you are talking about on Windoze/VC++.  Real developers use Unix ;-)
Regarding the nested includes in the Chromium guide, see the heading "Don't include unneeded headers"
I've never heard of Lakos, and I've been doing C++ for over 25 years (since the cfront days), and have work on really large projects like telecom software at Nortel.  The only bibles I know of in C/C++ are by K&R and Stroustrup.

**Comment by nerdralph** [comment]
Solved the lto issue with by setting CMAKE_AR and CMAKE_RANLIB  to gcc-ar and gcc-ranlib.
I was expecting additional size reduction compared to 4.8.4, but with 6.1 the binary is only about 1% smaller.

**Comment by bobsummerwill** [comment]
Build speedups are for all compilers, because all C++ toolsets are subject to the redundant work per compilation unit for the pre-processor.    Well, maybe pre-compiled headers can help a bit, but they really don't.

"Bible" in terms of physical dependencies in C++, which is something that most people don't even think about.    Do get yourself a copy if you haven't seen it.    I think that you will really enjoy it, though some of it looks a little dated.

1% smaller?   Yeah - not so hot!

**Comment by bobsummerwill** [comment]
I was just dicking about with BulkBuild on my MacBook Air.
Got `ethminer` build down to 3 mins.

**Comment by nerdralph** [comment]
@bobsummerwill If there was a way for you to lend me a copy of it, I'd read it, but I can't think of any books I consider worth $54!  My favorite book, "Blink" by Malcolm Gladwell costs less than $20 in paperback.

**Comment by nerdralph** [comment]
I just timed the build with gcc-6.1 (lto enabled), G1840 dual-core celeron, 2G RAM, 400G 2.5" SATA HD.
[100%] Built target ethminer
real    2m29.466s
user    2m21.188s
sys     0m5.648s

**Comment by bobsummerwill** [comment]
Second hand copies on Amazon from $2.50 + ~$4 for shipping.

Nice.  Linux certainly pisses on Mac for build times.    Your build times will be crazy fast with BulkBuild added too.

I'm seeing about 30mins -> 10 mins for the whole of cpp-ethereum, with some more work to do to unhack it into a state where I could commit.

**Comment by bobsummerwill** [comment]
They've got used copies on amazon.com from $2.50 + ~$4 shipping :-)

Getting 4mins for building the whole of `cpp-ethereum`, so all of the following, plus all the `.so`s as well:

- `bench`
- `eth`
- `ethkey`
- `ethminer`
- `rlp`
- `testeth`
- `testweb3`
- `testweb3core`

**Comment by bobsummerwill** [comment]
Fat finger!

**Comment by nerdralph** [comment]
@bobsummerwill That was just a single-threaded make.  make -j2 is even faster:
[100%] Built target ethminer
real    1m32.557s
user    2m30.144s
sys     0m6.228s

Normal development builds where you change a file or two and rebuild is in the range of 30s.

**Comment by nerdralph** [comment]
@bobsummerwill I found some of his book online (he published several articles in the C++ Report that went into the book).   Seems pretty mundane, and nothing I didn't already know so far.
The example of LakosianFooBars in the interface of the Bank class seems to be exactly what I was talking about when it comes to avoiding nested includes.

p.s. And the more I read the less I like it.  His Stack class uses an int for the index (d_sp) and size, while a smart developer would use unsigned int.

**Comment by bobsummerwill** [comment]
Well - no doubt plenty of his examples look dated for syntax, yes.
C++ syntax has advanced a lot since 1996.

His writing is primarily on physical dependencies and architecture - and really on the consequences of header files, compilation units, etc.

**Comment by nerdralph** [comment]
C++ has always had unsigned, and the pitfalls of using int for things that
should only have positive values was known even before C++ was invented.

On Aug 9, 2016 00:45, "Bob Summerwill" notifications@github.com wrote:

Well - no doubt plenty of his examples look dated for syntax, yes.
C++ syntax has advanced a lot since 1996.

His writing is primarily on physical dependencies and architecture - and
really on the consequences of header files, compilation units, etc.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/ethereum/webthree-umbrella/issues/495#issuecomment-238445753,
or mute the thread

**Comment by bobsummerwill** [comment]
Great - so my EOD time for cpp-ethereum building (all apps) is now 7 mins on my machine, where that process currently takes around 30-46 mins in Travis, depending on the OS X version.

I like those numbers.   Will clean it up tomorrow, to make a PR which could be submitted soon after the repo-move back to ethereum/cpp-ethereum.     I'll do a PR-on-a-PR-on-a-PR:

merge_repos -> cmake_fixes -> bulkbuild_support.

Good night!
