### ISSUE TITLE
MEGABUG - cpp-ethereum homecoming

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#639]
#634 Mega-bug to track the numerous threads of work in progress contributing towards our homecoming to https://github.com/ethereum/cpp-ethereum.
- [x] Content
  - [ ] Code review for [differences to cpp-ethereum](https://github.com/bobsummerwill/cpp-ethereum-with-history/commit/cbc0299282f196f4034a7696ef8d862e1b7609d1)
  - [ ] [History-preserving script](https://github.com/ethereum/webthree-umbrella/blob/develop/recreate-cpp-ethereum-with-history.sh)
- [x] Automated tests
  - [x] Appveyor - Windows Server 2012 
    - [ ] [Windows - Appveyor - 995 The I/O operation has been aborted](https://github.com/ethereum/webthree-umbrella/issues/640)
    - [ ] [Windows - Appveyor - Command exited with code -1073740791](https://github.com/ethereum/webthree-umbrella/issues/643)
  - [x] TravisCI - OS X Yosemite, OS X El Capitan, Ubuntu Trusty
    - [ ] [Ubuntu Trusty - libweb3core unit-test failure - 'ecies_sharedMacData'](https://github.com/ethereum/webthree-umbrella/issues/698)
    - [ ] [macOS - TravisCI - Just plain running out of time on the tests - 50 min limit](https://github.com/ethereum/webthree-umbrella/issues/620)
    - [ ] [TravisCI - Tons of "untagged" builds](https://github.com/ethereum/webthree-umbrella/issues/697)
- [ ] Release Flow
  - [x] Windows - ZIP
    - [ ] Windows - Looks like we are [missing DLLs from the ZIP](https://github.com/ethereum/webthree-umbrella/issues/665)
    - [ ] Windows - Documentation needs updating to point to VS2015 redist
  - [x] OS X Yosemite and El Capitan - ZIP
    - [X] Solidity ZIP needs dylib fixup, as per https://github.com/ethereum/solidity/issues/725
  - [x] Ubuntu - ZIP
  - [ ] OS X Yosemite and El Capitan - Homebrew
  - [ ] Ubuntu - Multiple PPAs
  - [ ] [We are implicitly dependent on Appveyor running faster than TravisCI](https://github.com/ethereum/webthree-umbrella/issues/658)
- [ ] Documentation
  - [x] README.md
  - [ ] Contributing - move to ethdocs.org
  - [ ] Coding standards - move to ethdocs.org
  - [ ] Update all the building from source and installing binaries instructions, using ...
  - [x] Infrastructure-as-code
    - [X] Windows - [install_deps.bat](https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.bat)
    - [x] Linux/UNIX - [install_deps.sh](https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh)
      - [X] - OS X Yosemite
      - [X] - OS X El Capitan
      - [X] - macOS Sierra
      - [X] - Ubuntu (Trusty, Utopic, Vivid, Wily, Xenial)
      - [X] - Ubuntu on Bash on Windows
      - [x] - Debian (Wheezy, Jessie, Stretch) - [Debian - Add support in install_deps.sh](https://github.com/ethereum/webthree-umbrella/issues/634)
      - [ ] - Alpine Linux- [Alpine - Add support in install_deps.sh](https://github.com/ethereum/webthree-umbrella/issues/633)
      - [ ] - Arch Linux - [Arch - Add support in install_deps.sh](https://github.com/ethereum/webthree-umbrella/issues/629)
      - [ ] - Fedora 20, 21, 22 - [Fedora - Add support in install_deps.sh](https://github.com/ethereum/webthree-umbrella/issues/631)
      - [ ] - openSUSE LEAP 42.1, Tangleweed - [openSUSE - Add support in install_deps.sh](https://github.com/ethereum/webthree-umbrella/issues/630)
      - [ ] - FreeBSD - [FreeBSD - Add support in install_deps.sh](https://github.com/ethereum/webthree-umbrella/issues/632)
      - [ ] - EthEmbedded (Rpi, BBB, Odroid, Wandboard, C.H.I.P)
      - [ ] - ARM Linux cross-builds
- [x] Other random TODOs
  - [x] Try some [BulkBuild-ing](https://github.com/bobsummerwill/cpp-ethereum/pull/6), to speed up the code builds
  - [ ] Blog post detailing this whole process, what has changed, etc.
  - [ ] Ensure that the LLVM 3.8 migration is complete for macOS
    - [ ] - https://github.com/ethereum/evmjit/pull/53
    - [ ] - https://github.com/ethereum/homebrew-ethereum/pull/67
  - [ ] Disable spammy progress %ages in cpp-dependencies

**Comment by bobsummerwill** [comment]
Priorities:

- Code actually works
- Working ZIPs
- Documentation
- Homebrew and PPA
- Clean diffs
- Clean history

**Comment by bobsummerwill** [comment]
Individual items remaining, but the MEGABUG is largely done with.
